words = [
  "abcdefghijklmopqrstuvwxyz",
  "aboveleft",
  "alphanum",
  "altfile",
  "augroup",
  "autocmd",
  "autocmds",
  "autojump",
  "autosession",
  "autosnippets",
  "bashls",
  "batcat",
  "bitbucket",
  "blines",
  "bmap",
  "bnext",
  "botleft",
  "botright",
  "bprevious",
  "breakindent",
  "breakpoint",
  "bufdelete",
  "bufferline",
  "bufferline's",
  "bufhidden",
  "buflisted",
  "bufnr",
  "buftype",
  "buftypes",
  "catppuccin",
  "changedelete",
  "checkhealth",
  "chmod",
  "cjs",
  "cli",
  "clickhandlers",
  "clickmod",
  "cmdheight",
  "cmdline",
  "cmdwin",
  "cnf",
  "codeberg",
  "codediff",
  "colwidth",
  "committerdate",
  "completeopt",
  "concealcursor",
  "conceallevel",
  "contenttypes",
  "copen",
  "cov",
  "cspell",
  "culhl",
  "cursorcolumn",
  "cursorline",
  "cursorlineopt",
  "cword",
  "dadbod",
  "dbname",
  "dbout",
  "dbui",
  "devicons",
  "dgo",
  "diffthis",
  "diffview",
  "dockerbake",
  "dockercompose",
  "dockerfiles",
  "dockerls",
  "dotenv",
  "dropbar",
  "dropbar's",
  "dto",
  "environmentvars",
  "eob",
  "esc",
  "expanders",
  "expandtab",
  "fdfind",
  "filesize",
  "filewatcher",
  "fillchar",
  "fillcharhl",
  "fillchars",
  "fixit",
  "fixup",
  "flavour",
  "fnm",
  "focusable",
  "foldclosed",
  "foldcolumn",
  "foldenable",
  "foldexpr",
  "foldlevel",
  "foldlevelstart",
  "foldmethod",
  "foldopen",
  "foldsep",
  "foldtext",
  "formatoptions",
  "frecency",
  "ftplugin",
  "fzf",
  "ghb",
  "ghd",
  "ghi",
  "ghp",
  "ghr",
  "ghs",
  "gitcommit",
  "gitdir",
  "gitrebase",
  "gitsigns",
  "globalstatus",
  "gra",
  "gri",
  "grn",
  "grr",
  "grt",
  "grx",
  "gtb",
  "gtw",
  "gxa",
  "gxb",
  "gxo",
  "gxq",
  "gxt",
  "habamax",
  "hcl",
  "healthcheck",
  "helptags",
  "hjkl",
  "hlgroup",
  "hlsearch",
  "ibl",
  "ide",
  "iglob",
  "ilent",
  "inccommand",
  "incsearch",
  "indentexpr",
  "jit",
  "johnnymorganz",
  "jsonls",
  "jsregexp",
  "jumpto",
  "kcu",
  "keeppatterns",
  "keymaps",
  "kulala",
  "langserver",
  "laststatus",
  "lastused",
  "lazygit",
  "lazypath",
  "lcov",
  "leftmouse",
  "libuv",
  "linehl",
  "listchars",
  "lnum",
  "loadplugins",
  "localleader",
  "localoptions",
  "loclist",
  "logpoint",
  "lspconfig",
  "lspconfig's",
  "lspinfo",
  "lua's",
  "luadoc",
  "lualine",
  "luasnip",
  "mapleader",
  "maplocalleader",
  "matchit",
  "maxwidth",
  "menuone",
  "mkdir",
  "modname",
  "mousemoveevent",
  "multicursor",
  "multiwindow",
  "myconfig",
  "nctrl",
  "ndesc",
  "ndto",
  "nent",
  "neogit",
  "neogit's",
  "neotest",
  "neotree",
  "neotreeignore",
  "neovim",
  "neovim's",
  "netrw",
  "newtab",
  "nmod",
  "nmsg",
  "nohlsearch",
  "nop",
  "noremap",
  "noselect",
  "nosplit",
  "notif",
  "npx",
  "nrepo",
  "nsvc",
  "ntest",
  "nui",
  "numhl",
  "nvic",
  "nvim",
  "nvim's",
  "nvm",
  "nxo",
  "nxso",
  "nzzzv",
  "oldfiles",
  "omni",
  "optim",
  "pathresolver",
  "prettierd",
  "prettierrc",
  "pty",
  "pumheight",
  "pwa",
  "qflist",
  "recenters",
  "reflog",
  "reinstalls",
  "relativenumber",
  "relculright",
  "rename's",
  "repointed",
  "require'nvim",
  "ripgrep",
  "rmq",
  "rtp",
  "scp",
  "scrolloff",
  "sessionoptions",
  "setopt",
  "shada",
  "shiftwidth",
  "showmode",
  "sidescrolloff",
  "signcolumn",
  "smartcase",
  "smartindent",
  "snr",
  "softtabstop",
  "splitbelow",
  "splitkeep",
  "splitright",
  "stackframe",
  "statuscol",
  "statuscol's",
  "statuscolumn",
  "statusline",
  "stdpath",
  "stylua",
  "sunmap",
  "swapfile",
  "switchbuf",
  "tabdo",
  "tabline",
  "tabnew",
  "tabpage",
  "tabpages",
  "tabstop",
  "tcc",
  "tcr",
  "tcs",
  "termguicolors",
  "texthl",
  "textobjects",
  "themable",
  "timeoutlen",
  "topdelete",
  "topline",
  "topo",
  "tsdk",
  "typeorm",
  "undescribed",
  "undofile",
  "undolevels",
  "unnamedplus",
  "unpulled",
  "updatetime",
  "urlencode",
  "uselast",
  "usetab",
  "usevisible",
  "vimdoc",
  "vimruntime",
  "vimscript",
  "virt",
  "virtualedit",
  "vitest",
  "vscode",
  "vsplit",
  "vtsls",
  "whichkey",
  "wildmode",
  "winbar",
  "winblend",
  "winborder",
  "wincmd",
  "winhighlight",
  "winopts",
  "winpos",
  "winrestview",
  "winsize",
  "wintypes",
  "winwidth",
  "worktree",
  "worktrees",
  "xxd",
  "yamlls",
  "zindex",
]
