local user = require("user.settings")
local icons = require("settings.icons")

local M = {}

M.cmd = "Neogit"

M.keys = {
  { "<leader>gg", "<cmd>Neogit<cr>", desc = "Neogit (status)" },
  { "<leader>gc", "<cmd>Neogit commit<cr>", desc = "Commit" },
  { "<leader>gp", "<cmd>Neogit push<cr>", desc = "Push" },
  { "<leader>gP", "<cmd>Neogit pull<cr>", desc = "Pull" },
  { "<leader>gl", "<cmd>Neogit log<cr>", desc = "Log" },
}

local fold_signs = { icons.ui.chevron_right, icons.ui.chevron_down }

M.opts = {
  treesitter_diff_highlight = false,
  word_diff_highlight = true,
  disable_hint = false,
  disable_context_highlighting = false,
  disable_signs = false,
  git_executable = "git",
  prompt_force_push = true,
  prompt_amend_commit = true,
  disable_insert_on_commit = "auto",
  filewatcher = { enabled = true },
  graph_style = "unicode",
  process_spinner = false,
  git_services = {
    ["github.com"] = {
      pull_request = "https://github.com/${owner}/${repository}/compare/${branch_name}?expand=1",
      commit = "https://github.com/${owner}/${repository}/commit/${oid}",
      tree = "https://${host}/${owner}/${repository}/tree/${branch_name}",
    },
    ["bitbucket.org"] = {
      pull_request = "https://bitbucket.org/${owner}/${repository}/pull-requests/new?source=${branch_name}&t=1",
      commit = "https://bitbucket.org/${owner}/${repository}/commits/${oid}",
      tree = "https://bitbucket.org/${owner}/${repository}/branch/${branch_name}",
    },
    ["gitlab.com"] = {
      pull_request = "https://gitlab.com/${owner}/${repository}/merge_requests/new?merge_request[source_branch]=${branch_name}",
      commit = "https://gitlab.com/${owner}/${repository}/-/commit/${oid}",
      tree = "https://gitlab.com/${owner}/${repository}/-/tree/${branch_name}?ref_type=heads",
    },
    ["azure.com"] = {
      pull_request = "https://dev.azure.com/${owner}/_git/${repository}/pullrequestcreate?sourceRef=${branch_name}&targetRef=${target}",
      commit = "",
      tree = "",
    },
    ["codeberg.org"] = {
      pull_request = "https://${host}/${owner}/${repository}/compare/${branch_name}",
      commit = "https://${host}/${owner}/${repository}/commit/${oid}",
      tree = "https://${host}/${owner}/${repository}/src/branch/${branch_name}",
    },
  },
  remember_settings = true,
  use_per_project_settings = true,
  ignored_settings = {},
  highlight = { italic = true, bold = true, underline = true },
  use_default_keymaps = true,
  sort_branches = "-committerdate",
  commit_order = "topo",
  initial_branch_name = "",
  kind = "tab",
  floating = {
    relative = "editor",
    width = 0.8,
    height = 0.7,
    style = "minimal",
    border = user.ui.border,
  },
  disable_line_numbers = true,
  disable_relative_line_numbers = true,
  console_timeout = 2000,
  auto_show_console = true,
  auto_close_console = true,
  notification_icon = icons.keymap_groups.git,
  status = {
    show_head_commit_hash = true,
    recent_commit_count = 10,
    HEAD_padding = 10,
    HEAD_folded = false,
    mode_padding = 3,
    mode_text = {
      M = "modified",
      N = "new file",
      A = "added",
      D = "deleted",
      C = "copied",
      U = "updated",
      R = "renamed",
      T = "changed",
      DD = "unmerged",
      AU = "unmerged",
      UD = "unmerged",
      UA = "unmerged",
      DU = "unmerged",
      AA = "unmerged",
      UU = "unmerged",
      ["?"] = "",
    },
  },
  commit_editor = {
    kind = "split",
    show_staged_diff = true,
    staged_diff_split_kind = "split",
    spell_check = false,
  },
  commit_select_view = { kind = "tab" },
  commit_view = { kind = "vsplit", verify_commit = false },
  log_view = { kind = "tab" },
  rebase_editor = { kind = "auto" },
  reflog_view = { kind = "tab" },
  merge_editor = { kind = "auto" },
  preview_buffer = { kind = "floating_console" },
  popup = { kind = "split", show_title = false },
  stash = { kind = "tab" },
  refs_view = { kind = "tab" },
  signs = {
    hunk = { "", "" },
    item = fold_signs,
    section = fold_signs,
  },
  integrations = {
    telescope = false,
    diffview = true,
    codediff = false,
    fzf_lua = true,
    mini_pick = false,
    snacks = false,
  },
  diff_viewer = "diffview",
  sections = {
    sequencer = { folded = false, hidden = false },
    untracked = { folded = false, hidden = false },
    unstaged = { folded = false, hidden = false },
    staged = { folded = false, hidden = false },
    stashes = { folded = true, hidden = false },
    unpulled_upstream = { folded = true, hidden = false },
    unmerged_upstream = { folded = false, hidden = false },
    unpulled_pushRemote = { folded = true, hidden = false },
    unmerged_pushRemote = { folded = false, hidden = false },
    recent = { folded = true, hidden = false },
    rebase = { folded = true, hidden = false },
  },
  mappings = {
    commit_editor = {
      ["q"] = "Close",
      ["<localleader>c"] = "Submit",
      ["<localleader>k"] = "Abort",
      ["<localleader>p"] = "PrevMessage",
      ["<localleader>n"] = "NextMessage",
      ["<localleader>r"] = "ResetMessage",
      ["<c-c><c-c>"] = false,
      ["<c-c><c-k>"] = false,
      ["<m-p>"] = false,
      ["<m-n>"] = false,
      ["<m-r>"] = false,
    },
    commit_editor_I = {
      ["<c-c><c-c>"] = false,
      ["<c-c><c-k>"] = false,
    },
    commit_view = {
      ["a"] = "OpenFileInWorktree",
    },
    rebase_editor = {
      ["p"] = "Pick",
      ["r"] = "Reword",
      ["e"] = "Edit",
      ["s"] = "Squash",
      ["f"] = "Fixup",
      ["x"] = "Execute",
      ["d"] = "Drop",
      ["b"] = "Break",
      ["q"] = "Close",
      ["<cr>"] = "OpenCommit",
      ["gk"] = "MoveUp",
      ["gj"] = "MoveDown",
      ["<localleader>c"] = "Submit",
      ["<localleader>k"] = "Abort",
      ["[o"] = "OpenOrScrollUp",
      ["]o"] = "OpenOrScrollDown",
      ["<c-c><c-c>"] = false,
      ["<c-c><c-k>"] = false,
      ["[c"] = false,
      ["]c"] = false,
    },
    rebase_editor_I = {
      ["<c-c><c-c>"] = false,
      ["<c-c><c-k>"] = false,
    },
    finder = {
      ["<cr>"] = "Select",
      ["<esc>"] = "Close",
      ["<c-c>"] = false,
      ["<c-n>"] = "Next",
      ["<c-p>"] = "Previous",
      ["<down>"] = "Next",
      ["<up>"] = "Previous",
      ["<tab>"] = "InsertCompletion",
      ["<c-y>"] = "CopySelection",
      ["<space>"] = "MultiselectToggleNext",
      ["<s-space>"] = "MultiselectTogglePrevious",
      ["<c-j>"] = "NOP",
      ["<ScrollWheelDown>"] = "ScrollWheelDown",
      ["<ScrollWheelUp>"] = "ScrollWheelUp",
      ["<ScrollWheelLeft>"] = "NOP",
      ["<ScrollWheelRight>"] = "NOP",
      ["<LeftMouse>"] = "MouseClick",
      ["<2-LeftMouse>"] = "NOP",
    },
    popup = {
      ["?"] = "HelpPopup",
      ["A"] = "CherryPickPopup",
      ["d"] = "DiffPopup",
      ["M"] = "RemotePopup",
      ["P"] = "PushPopup",
      ["X"] = "ResetPopup",
      ["Z"] = "StashPopup",
      ["i"] = "IgnorePopup",
      ["t"] = "TagPopup",
      ["b"] = "BranchPopup",
      ["B"] = "BisectPopup",
      ["w"] = "WorktreePopup",
      ["c"] = "CommitPopup",
      ["f"] = "FetchPopup",
      ["l"] = "LogPopup",
      ["L"] = "MarginPopup",
      ["m"] = "MergePopup",
      ["p"] = "PullPopup",
      ["r"] = "RebasePopup",
      ["v"] = "RevertPopup",
    },
    status = {
      ["j"] = "MoveDown",
      ["k"] = "MoveUp",
      ["o"] = "OpenTree",
      ["q"] = "Close",
      ["I"] = "InitRepo",
      ["1"] = "Depth1",
      ["2"] = "Depth2",
      ["3"] = "Depth3",
      ["4"] = "Depth4",
      ["Q"] = "Command",
      ["<tab>"] = "Toggle",
      ["za"] = "Toggle",
      ["zo"] = "OpenFold",
      ["x"] = "Discard",
      ["-"] = "Reverse",
      ["s"] = "Stage",
      ["S"] = "StageUnstaged",
      ["<localleader>a"] = "StageAll",
      ["<c-s>"] = false,
      ["u"] = "Unstage",
      ["K"] = "Untrack",
      ["U"] = "UnstageStaged",
      ["y"] = "ShowRefs",
      ["$"] = "CommandHistory",
      ["Y"] = "YankSelected",
      ["gp"] = "GoToParentRepo",
      ["<c-r>"] = "RefreshBuffer",
      ["<cr>"] = "GoToFile",
      ["<s-cr>"] = "PeekFile",
      ["<localleader>v"] = "VSplitOpen",
      ["<localleader>s"] = "SplitOpen",
      ["<localleader>t"] = "TabOpen",
      ["<c-v>"] = false,
      ["<c-x>"] = false,
      ["<c-t>"] = false,
      ["{"] = "GoToPreviousHunkHeader",
      ["}"] = "GoToNextHunkHeader",
      ["[o"] = "OpenOrScrollUp",
      ["]o"] = "OpenOrScrollDown",
      ["[c"] = false,
      ["]c"] = false,
      ["<c-k>"] = "PeekUp",
      ["<c-j>"] = "PeekDown",
      ["<c-n>"] = "NextSection",
      ["<c-p>"] = "PreviousSection",
    },
  },
}

local descriptions = {
  popup = {
    HelpPopup = "Help",
    CherryPickPopup = "Cherry-pick",
    DiffPopup = "Diff",
    RemotePopup = "Remote",
    PushPopup = "Push",
    ResetPopup = "Reset",
    StashPopup = "Stash",
    IgnorePopup = "Ignore",
    TagPopup = "Tag",
    BranchPopup = "Branch",
    BisectPopup = "Bisect",
    WorktreePopup = "Worktree",
    CommitPopup = "Commit",
    FetchPopup = "Fetch",
    LogPopup = "Log",
    MarginPopup = "Margin",
    MergePopup = "Merge",
    PullPopup = "Pull",
    RebasePopup = "Rebase",
    RevertPopup = "Revert",
  },
  status = {
    MoveDown = "Next item",
    MoveUp = "Previous item",
    OpenTree = "Open tree in browser",
    Close = "Close",
    InitRepo = "Init repository",
    Depth1 = "Fold to sections",
    Depth2 = "Fold to files",
    Depth3 = "Fold to hunks",
    Depth4 = "Unfold everything",
    Command = "Run git command",
    Toggle = "Toggle fold",
    OpenFold = "Open fold",
    Discard = "Discard",
    Reverse = "Reverse change",
    Stage = "Stage",
    StageUnstaged = "Stage all unstaged",
    StageAll = "Stage everything",
    Unstage = "Unstage",
    Untrack = "Untrack",
    UnstageStaged = "Unstage everything",
    ShowRefs = "Show refs",
    CommandHistory = "Git command history",
    YankSelected = "Yank",
    GoToParentRepo = "Go to parent repository",
    RefreshBuffer = "Refresh",
    GoToFile = "Open item under cursor",
    PeekFile = "Peek item under cursor",
    VSplitOpen = "Open in vertical split",
    SplitOpen = "Open in split",
    TabOpen = "Open in tab",
    GoToPreviousHunkHeader = "Previous hunk header",
    GoToNextHunkHeader = "Next hunk header",
    OpenOrScrollUp = "Open or scroll preview up",
    OpenOrScrollDown = "Open or scroll preview down",
    PeekUp = "Peek previous",
    PeekDown = "Peek next",
    NextSection = "Next section",
    PreviousSection = "Previous section",
  },
  commit_view = {
    OpenFileInWorktree = "Open file in worktree",
  },
  commit_editor = {
    Close = "Close",
    Submit = "Submit",
    Abort = "Abort",
    PrevMessage = "Previous message",
    NextMessage = "Next message",
    ResetMessage = "Reset message",
  },
  rebase_editor = {
    Pick = "Pick",
    Reword = "Reword",
    Edit = "Edit",
    Squash = "Squash",
    Fixup = "Fixup",
    Execute = "Execute",
    Drop = "Drop",
    Break = "Break",
    Close = "Close",
    OpenCommit = "Open commit",
    MoveUp = "Move commit up",
    MoveDown = "Move commit down",
    Submit = "Submit",
    Abort = "Abort",
    OpenOrScrollUp = "Open or scroll preview up",
    OpenOrScrollDown = "Open or scroll preview down",
  },
}

local view_actions = {
  Close = true,
  Toggle = true,
  Reverse = true,
  GoToFile = true,
  PeekFile = true,
  PeekUp = true,
  PeekDown = true,
  OpenOrScrollUp = true,
  OpenOrScrollDown = true,
  YankSelected = true,
  RefreshBuffer = true,
}

local buffer_groups = {
  NeogitStatus = { "status", "popup" },
  NeogitCommitView = { "commit_view", "view", "popup" },
  NeogitLogView = { "view", "popup" },
  NeogitReflogView = { "view", "popup" },
  NeogitRefsView = { "view", "popup" },
  NeogitStashView = { "view", "popup" },
  NeogitCommitSelectView = { "view" },
  NeogitDiffView = { "view" },
  NeogitGitCommandHistory = { "view" },
  NeogitConsole = { "view" },
  gitcommit = { "commit_editor" },
  gitrebase = { "rebase_editor" },
}

local function describe_keymaps(buf, groups, mappings)
  for _, group in ipairs(groups) do
    local source = group == "view" and "status" or group
    for key, action in pairs(mappings[source] or {}) do
      local desc = descriptions[source][action]
      if desc and (group ~= "view" or view_actions[action]) then
        for _, mode in ipairs({ "n", "v" }) do
          local map = vim.fn.maparg(key, mode, false, true)
          if map.buffer == 1 and not map.desc then
            map.desc = desc
            vim.fn.mapset(map)
          end
        end
      end
    end
  end
end

function M.config(_, opts)
  require("neogit").setup(opts)

  vim.api.nvim_create_autocmd("FileType", {
    group = vim.api.nvim_create_augroup("settings_neogit", { clear = true }),
    pattern = vim.tbl_keys(buffer_groups),
    desc = "Describe neogit buffer keymaps",
    callback = function(event)
      local groups = buffer_groups[event.match]
      vim.schedule(function()
        if vim.api.nvim_buf_is_valid(event.buf) then
          vim.api.nvim_buf_call(event.buf, function()
            describe_keymaps(event.buf, groups, opts.mappings)
          end)
        end
      end)
    end,
  })
end

return M
